title: Beginner Website
description: In the tutorial you will build a simple static website with HTML, CSS and Javascript
remote_theme: pmarsceill/just-the-docs
search_enabled: true
ga_tracking: UA-146945738-8
aux_links:
    "Coding Skills.IO":
      - "https://rclapp.com"
footer_content: "Copyright &copy; 2020 Ray Consulting Limited. Distributed by an <a href=\"https://github.com/rcl-coding/tutorial-staticwebsite/blob/master/LICENSE\">MIT license.</a>"
plugins:
  - jekyll-seo-tag